import Navbar from "@/components/navbar";
import Providers from "@/components/providers";
import Sidebar from "@/components/sidebar";
import { cn } from "@/lib/utils";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("antialiased", inter.className)}>
      <body>
        <Script
          src="/daisy-multiselect.js"
          strategy="afterInteractive"
        ></Script>

        <Providers>
          <div className="drawer lg:drawer-open">
            <input id="my-drawer" type="checkbox" className="drawer-toggle" />
            <Sidebar />

            <div className="drawer-content">
              <Navbar />

              <div className="p-4">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
