import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import "@progress/kendo-theme-default/dist/all.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased", inter.className)}
      data-theme="light"
      suppressContentEditableWarning
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
